from datetime import datetime, UTC
from sqlalchemy import ForeignKey, Integer, String, Float, DateTime
from sqlalchemy.orm import Mapped, mapped_column, relationship, declarative_base

Base = declarative_base()


class Enrollment(Base):
    __tablename__ = "enrollment"

    student_id: Mapped[int] = mapped_column(ForeignKey("student.id"), primary_key=True)
    course_id: Mapped[int] = mapped_column(ForeignKey("course.id"), primary_key=True)
    enrolled_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now(UTC))
    progress_pct: Mapped[float] = mapped_column(Float, default=0.0)
    certificate_url: Mapped[str] = mapped_column(String, nullable=True)

    student: Mapped["Student"] = relationship("Student", back_populates="courses_assoc")
    course: Mapped["Course"] = relationship("Course", back_populates="students_assoc")


class Teacher(Base):
    __tablename__ = "teacher"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String, nullable=False)

    courses: Mapped[list["Course"]] = relationship("Course", back_populates="teacher")


class Course(Base):
    __tablename__ = "course"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    title: Mapped[str] = mapped_column(String, nullable=False)
    teacher_id: Mapped[int] = mapped_column(ForeignKey("teacher.id"))

    teacher: Mapped["Teacher"] = relationship("Teacher", back_populates="courses")
    lessons: Mapped[list["Lesson"]] = relationship("Lesson", back_populates="course", order_by="Lesson.order_num")

    students_assoc: Mapped[list["Enrollment"]] = relationship("Enrollment", back_populates="course")
    students: Mapped[list["Student"]] = relationship("Student", secondary="enrollment", viewonly=True)


class Lesson(Base):
    __tablename__ = "lesson"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    title: Mapped[str] = mapped_column(String, nullable=False)
    course_id: Mapped[int] = mapped_column(ForeignKey("course.id"))
    order_num: Mapped[int] = mapped_column(Integer, default=0)

    course: Mapped["Course"] = relationship("Course", back_populates="lessons")
    submissions: Mapped[list["Submission"]] = relationship("Submission", back_populates="lesson")


class Student(Base):
    __tablename__ = "student"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String, nullable=False)

    courses_assoc: Mapped[list["Enrollment"]] = relationship("Enrollment", back_populates="student")
    courses: Mapped[list["Course"]] = relationship("Course", secondary="enrollment", viewonly=True)



class Submission(Base):
    __tablename__ = "submission"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    student_id: Mapped[int] = mapped_column(ForeignKey("student.id"))
    lesson_id: Mapped[int] = mapped_column(ForeignKey("lesson.id"))
    score: Mapped[float] = mapped_column(Float, default=0.0)

    student: Mapped["Student"] = relationship("Student")
    lesson: Mapped["Lesson"] = relationship("Lesson", back_populates="submissions")

    @property
    def is_passed(self) -> bool:
        return self.score >= 60

# """initial

# Revision ID: fb1f3ec9aedf
# Revises:
# Create Date: 2026-03-09 17:48:41.813466

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = 'fb1f3ec9aedf'
# down_revision: Union[str, Sequence[str], None] = None
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('student',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(), nullable=False),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('teacher',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(), nullable=False),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('course',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('title', sa.String(), nullable=False),
#     sa.Column('teacher_id', sa.Integer(), nullable=False),
#     sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('enrollment',
#     sa.Column('student_id', sa.Integer(), nullable=False),
#     sa.Column('course_id', sa.Integer(), nullable=False),
#     sa.Column('enrolled_at', sa.DateTime(), nullable=False),
#     sa.Column('progress_pct', sa.Float(), nullable=False),
#     sa.Column('certificate_url', sa.String(), nullable=True),
#     sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
#     sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
#     sa.PrimaryKeyConstraint('student_id', 'course_id')
#     )
#     op.create_table('lesson',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('title', sa.String(), nullable=False),
#     sa.Column('course_id', sa.Integer(), nullable=False),
#     sa.Column('order_num', sa.Integer(), nullable=False),
#     sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('submission',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('student_id', sa.Integer(), nullable=False),
#     sa.Column('lesson_id', sa.Integer(), nullable=False),
#     sa.Column('score', sa.Float(), nullable=False),
#     sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
#     sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('submission')
#     op.drop_table('lesson')
#     op.drop_table('enrollment')
#     op.drop_table('course')
#     op.drop_table('teacher')
#     op.drop_table('student')
#     # ### end Alembic commands ###
